version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 5555:80
        volumes:
            - ./server:/var/www/html

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
         - ./sql/db.sql:/docker-entrypoint-initdb.d/db.sql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1

    node:
        build:
          context: .
        volumes:
          - ./front:/app
          - /node_modules
        ports:
          - 3000:3000
        environment:
          - CHOKIDAR_USEPOLLING=true

volumes:
    sql:
